"use client";

import { useCallback, useEffect, useRef, useState, type FormEvent } from "react";
import { ArrowDownUp, ArrowUpRight, Asterisk, Camera, Check, ChevronRight, Globe2, ImagePlus, Info, LoaderCircle, Package, Search, ShieldCheck, SlidersHorizontal, Sparkles, X } from "lucide-react";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { marketplaces, searchQuery } from "@/lib/marketplaces";
import { referenceListings, matchesReference } from "@/lib/reference-listings";
import { scoreSeller, scoreListing, landedCost } from "@/lib/scoring";
import { unknownEvidence, type Lane, type Listing, type SearchResponse } from "@/lib/finder-types";

const initialQuery="Rick Owens bias bootcut jeans";
const money=(n:number|null,currency="USD")=>n===null?"Price unavailable":new Intl.NumberFormat("en-US",{style:"currency",currency,maximumFractionDigits:2}).format(n);
type Connections={ebay:boolean;search:boolean;vision:boolean};

export default function Finder(){
 const [query,setQuery]=useState(initialQuery),[searched,setSearched]=useState(initialQuery),[lane,setLane]=useState<Lane>("legit");
 const [listings,setListings]=useState<Listing[]>(referenceListings),[selected,setSelected]=useState<Listing|null>(null);
 const [manualListings,setManualListings]=useState<Listing[]>([]),[overrides,setOverrides]=useState<Record<string,Listing>>({});
 const [platform,setPlatform]=useState("all"),[sort,setSort]=useState("match"),[budget,setBudget]=useState("");
 const [size,setSize]=useState("all"),[busy,setBusy]=useState(false),[message,setMessage]=useState("Researched listings · Sep 12, 2026 · recheck price and availability on the source.");
 const [image,setImage]=useState<string|null>("/reference-jeans.png"),[imageName,setImageName]=useState("Your reference"),[visionBusy,setVisionBusy]=useState(false);
 const [connections,setConnections]=useState<Connections>({ebay:false,search:false,vision:false}),[settings,setSettings]=useState(false),[importOpen,setImportOpen]=useState(false);
 const fileInput=useRef<HTMLInputElement>(null); const request=useRef<AbortController|null>(null); const requestId=useRef(0);
 useEffect(()=>{fetch("/api/status").then(r=>r.json()).then(value=>setConnections(value as Connections)).catch(()=>{});return()=>request.current?.abort();},[]);
 const runSearch=useCallback(async(q:string,category:Lane)=>{
   if(!q.trim())return; const id=++requestId.current;request.current?.abort();const controller=new AbortController();request.current=controller;
   setQuery(q);setSearched(q);setLane(category);setPlatform("all");setBusy(true);setListings([]);setMessage("Searching connected sources…");
   try { const response=await fetch("/api/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:q,lane:category}),signal:controller.signal}); const data:SearchResponse&{error?:string}=await response.json();if(!response.ok)throw new Error(data.error||"Search unavailable");if(id!==requestId.current)return;setListings(data.listings);setMessage(data.message+(data.errors.length?` ${data.errors.join(" ")}`:"")); }
   catch(error){if(controller.signal.aborted)return;setListings(category==="legit"&&matchesReference(q)?referenceListings:[]);setMessage(error instanceof Error?error.message:"Search failed. Use the marketplace links below.");}
   finally{if(id===requestId.current)setBusy(false);}
 },[]);
 useEffect(()=>{
   const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;
   if(!context?.registerTool)return;const lifecycle=new AbortController();
   try{Promise.resolve(context.registerTool({name:"search_clothing",title:"Search clothing",description:"Search connected clothing sources and update the visible Legit or Reps results. Does not buy or contact sellers.",inputSchema:{type:"object",properties:{query:{type:"string",minLength:2,maxLength:180},lane:{type:"string",enum:["legit","reps"]}},required:["query","lane"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{const p=input as {query?:unknown;lane?:unknown};if(typeof p?.query!=="string"||p.query.trim().length<2||p.query.length>180||(p.lane!=="legit"&&p.lane!=="reps"))throw new Error("Provide a query and a valid lane");await runSearch(p.query,p.lane);return {query:p.query,lane:p.lane,status:"Search finished; inspect visible results and source status"};}}, {signal:lifecycle.signal})).catch(()=>{});}catch{}
   return()=>lifecycle.abort();
 },[runSearch]);
 async function upload(file:File|undefined){
   if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>5*1024*1024){setMessage("Choose a JPG, PNG, or WebP image under 5 MB.");return;}
   const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);});
   setImage(data);setImageName(file.name);setMessage("Image added. Identify it to suggest search terms, or enter a title above.");
 }
 async function identify(){
   if(!image)return;if(!connections.vision){setSettings(true);return;}
   setVisionBusy(true);
   try{let data=image;if(image.startsWith("/")){const blob=await(await fetch(image)).blob();data=await new Promise<string>(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.readAsDataURL(blob);});}
    const response=await fetch("/api/identify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({image:data})});const result=await response.json() as {query:string;error?:string};if(!response.ok)throw new Error(result.error);setQuery(result.query);setMessage("Suggested search terms added. Review the title, then find listings. Image identification is not authentication.");
   }catch(e){setMessage(e instanceof Error?e.message:"Image identification failed");}finally{setVisionBusy(false);}
 }
 const sources=marketplaces.filter(m=>m.lanes.includes(lane));
 const allListings=[...manualListings.filter(l=>l.searchQuery?.toLowerCase()===searched.toLowerCase()),...listings].map(l=>overrides[l.id]??l);
 const results=allListings.filter(l=>l.lane===lane&&(platform==="all"||l.platform===platform)&&(size==="all"||l.size===size)&&(!budget||(l.currency==="USD"&&l.price!==null&&l.price<=Number(budget)))).sort((a,b)=>sort==="trust"?(scoreListing(b).score??-1)-(scoreListing(a).score??-1):sort==="price"?(a.currency==="USD"?a.price??Infinity:Infinity)-(b.currency==="USD"?b.price??Infinity:Infinity):Number(b.match==="close")-Number(a.match==="close"));
 const lowest=results.filter(l=>l.match==="close"&&l.price!==null&&l.currency==="USD"&&l.availability!=="sold-out").sort((a,b)=>a.price!-b.price!)[0];
 return <div className="finder-shell">
  <header className="topbar"><a href="/" className="brand"><span className="brand-mark"><Asterisk size={27}/></span>clothing finder<span className="beta">WORKSPACE</span></a><div className="top-actions"><span className="destination"><Globe2 size={15}/> Ship to US · USD</span><button className="connection-button" onClick={()=>setSettings(true)}><span className={connections.ebay||connections.search?"status-dot connected":"status-dot"}/>{connections.ebay||connections.search?"Live sources":"Source setup"}<ChevronRight size={14}/></button></div></header>
  <main className="main-wrap"><div className="page-heading"><div><div className="eyebrow">THE SEARCH IS PART OF THE FIND</div><h1>Find your piece.</h1><p>One search. More places to look.</p></div><div className="heading-index">01 / DISCOVER</div></div>
   <form className="search-bar" onSubmit={(e)=>{e.preventDefault();void runSearch(query,lane);}}><Search size={21}/><input aria-label="Item title or description" maxLength={180} value={query} onChange={e=>setQuery(e.target.value)} placeholder="A brand, a piece, a very specific obsession…"/><button type="button" aria-label="Add image" className="image-search-button" onClick={()=>fileInput.current?.click()}><Camera size={18}/><span>Add image</span></button><button aria-label="Find listings" className="primary-button" disabled={busy||!query.trim()}>{busy?<LoaderCircle className="spin" size={17}/>:<Search size={17}/>}<span>{busy?"Searching":"Find listings"}</span></button></form>
   <input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" ref={fileInput} onChange={e=>{void upload(e.target.files?.[0]);e.target.value="";}}/>
   <Tabs value={lane} onValueChange={value=>{void runSearch(query,value as Lane);}} className="lane-tabs"><div className="tab-row"><TabsList variant="line"><TabsTrigger value="legit"><ShieldCheck size={17}/>Legit<span className="tab-caption">Resale & retail</span></TabsTrigger><TabsTrigger value="reps"><LayersIcon/>Reps<span className="tab-caption">Alternatives & proxies</span></TabsTrigger></TabsList><span className="tab-note">{lane==="legit"?"Listed as authentic. Always verify the item.":"Replica candidates. A marketplace is not an authenticity label."}</span></div></Tabs>
   <div className="workspace-grid"><aside className="reference-column"><div className="section-kicker">YOUR REFERENCE <span>01</span></div><div className="reference-image" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void upload(e.dataTransfer.files?.[0]);}}>{image?<img src={image} alt="Uploaded clothing reference"/>:<ImagePlus size={44}/>}<button className="replace-image" aria-label="Replace reference image" onClick={()=>fileInput.current?.click()}><ImagePlus size={17}/></button>{image&&image!=="/reference-jeans.png"&&<button className="remove-image" aria-label="Remove reference image" onClick={()=>setImage(null)}><X size={16}/></button>}</div><div className="reference-caption">{imageName}</div>{image==="/reference-jeans.png"?<><h2>Rick Owens</h2><p className="reference-description">Bias bootcut · black / pearl degrade</p><span className="small-label">VISUAL MATCH TO RESEARCH · UNCONFIRMED</span></>:<p className="reference-description">Add a title or identify this image to start your search.</p>}<button className="outline-button identify-button" onClick={()=>void identify()} disabled={!image||visionBusy}><Sparkles size={15}/>{visionBusy?"Identifying…":"Identify image"}</button><div className="reference-rule"/><div className="section-kicker"><SlidersHorizontal size={14}/> REFINE RESULTS</div><label className="field-label">Waist size<Select value={size} onValueChange={setSize}><SelectTrigger className="filter-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All sizes</SelectItem>{[...new Set(allListings.filter(l=>l.lane===lane).map(l=>l.size))].filter(s=>s!=="Not specified").sort().map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></label><label className="field-label">Maximum item price (USD)<div className="budget-input"><span>$</span><input type="number" min="0" aria-label="Maximum item price in USD" value={budget} onChange={e=>setBudget(e.target.value)} placeholder="No limit"/></div></label>{budget&&<p className="microcopy">Unknown prices and other currencies are hidden.</p>}<button className="text-button reset-button" onClick={()=>{setBudget("");setSize("all");setPlatform("all");}}>Reset filters</button><div className="trust-note"><ShieldCheck size={20}/><h3>Good price. Better evidence.</h3><p>No sales, no listings, and a price that looks too low? That should lower trust, not raise your hopes.</p><button className="text-button" onClick={()=>setSettings(true)}>How scoring works <ArrowUpRight size={13}/></button></div></aside>
   <section className="results-column" aria-label="Search results"><div className="results-heading"><div><div className="section-kicker">{lane==="legit"?"THE SHORTLIST":"THE ALTERNATIVE ROUTE"}</div><h2>{lane==="legit"?"Worth a closer look.":"Find the look, compare the cost."}</h2></div><button className="outline-button import-button" onClick={()=>setImportOpen(true)}>+ Add a listing</button></div>
    <div className="source-filters"><button className={platform==="all"?"chip active":"chip"} onClick={()=>setPlatform("all")}>All marketplaces</button>{sources.slice(0,lane==="legit"?7:3).map(s=><button className={platform===s.name?"chip active":"chip"} key={s.id} onClick={()=>setPlatform(s.name)}>{s.name}</button>)}</div>
    <div className="result-meta"><span><strong>{results.length}</strong> {results.length===1?"listing":"listings"}{lowest&&<> <span className="meta-divider">/</span> Close matches from <strong>{money(lowest.price)}</strong></>}</span><div className="sort-control"><ArrowDownUp size={13}/><Select value={sort} onValueChange={setSort}><SelectTrigger aria-label="Sort listings"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="match">Closest match</SelectItem><SelectItem value="price">Lowest item price · USD</SelectItem><SelectItem value="trust">Seller trust</SelectItem></SelectContent></Select></div></div>
    <div className="source-status" role="status"><Info size={14}/><span>{message}</span></div>
    {busy?<div className="empty-results"><LoaderCircle size={28} className="spin"/><h3>Looking for your piece…</h3><p>Checking connected sources for “{searched}”.</p></div>:results.length?<div className="listing-grid">{results.map((listing)=><ListingCard key={listing.id} listing={listing} onSelect={()=>setSelected(listing)} lowest={listing.id===lowest?.id}/>)}</div>:<div className="empty-results"><Search size={28}/><h3>{platform!=="all"||size!=="all"||budget?"No listings match these filters.":lane==="reps"?"Start with a marketplace search.":"Your next find is out there."}</h3><p>{lane==="reps"?"Browse candidates below, then add a listing to evaluate the seller and estimate its delivered cost.":"Open a marketplace below or connect live search. Missing results do not mean the item is unavailable."}</p></div>}
    {lane==="reps"&&<CostCalculator/>}
    <div className="marketplace-heading"><h3>Keep looking</h3><span>Search “{searched}” on the source <ArrowUpRight size={14}/></span></div><div className="marketplace-grid">{sources.map(s=><a key={s.id} href={s.search(searchQuery(searched,lane))} target="_blank" rel="noopener noreferrer" className="marketplace-link"><span className={`marketplace-initial ${s.id}`}>{s.name.slice(0,1)}</span><div><strong>{s.name}</strong><span>{s.hint}</span><small>{s.route} · opens search</small></div><ArrowUpRight size={17}/></a>)}</div>
    {lane==="reps"&&<div className="proxy-note"><Package size={19}/><p><strong>From seller to warehouse to you.</strong> Confirm the buying agent accepts the item, ask for warehouse photos, and add international shipping before comparing deals. Japanese resale is in Legit; proxy use does not establish authenticity.</p><a href="https://bc.help.buyee.jp/en/fee/" target="_blank" rel="noopener noreferrer">Proxy fee guide <ArrowUpRight size={13}/></a></div>}
   </section></div><footer><span><Asterisk size={15}/> clothing finder</span><span>Check the piece. Check the seller. Then decide.</span><span>USD · US destination</span></footer>
  </main>
  <Sheet open={!!selected} onOpenChange={v=>{if(!v)setSelected(null);}}><SheetContent className="detail-sheet">{selected&&<ListingDetails listing={selected} onUpdate={l=>{setOverrides(old=>({...old,[l.id]:l}));setSelected(l);}}/>}</SheetContent></Sheet>
  <Sheet open={settings} onOpenChange={setSettings}><SheetContent className="detail-sheet"><SheetHeader><span className="eyebrow">BEHIND THE FIND</span><SheetTitle>Sources & seller trust</SheetTitle><SheetDescription>See what is connected and how a score is made.</SheetDescription></SheetHeader><div className="sheet-body"><h3>Connected sources</h3>{[["eBay Browse",connections.ebay,"Live keyword search with seller feedback"],["Brave Search",connections.search,"Find indexed listings across marketplaces"],["Image identification",connections.vision,"Suggest search terms from your photo"]].map(([name,ready,description])=><div className="connection-row" key={String(name)}><div><strong>{name}</strong><p>{description}</p></div><span className={ready?"pill good":"pill neutral"}>{ready?"Connected":"Not configured"}</span></div>)}<p className="detail-note">Configure optional keys in this project’s .env file, then restart. Marketplace links and researched listings work without keys. Private or login-only inventory requires opening the source.</p><h3>Trust is earned through evidence</h3><p>Scores consider sales history, active listings, feedback volume and quality, account age, and verified photo evidence. Missing data stays unknown.</p><div className="trust-scale"><span>0–34<br/><b>High risk</b></span><span>35–59<br/><b>Caution</b></span><span>60–79<br/><b>Some evidence</b></span><span>80–98<br/><b>Strong history</b></span></div><p>With no recorded sales, no active listings, and a price below 40% of at least three comparable items, trust is capped at 25. Without enough evidence, a numeric score is withheld.</p><p className="detail-note">A heuristic score is not a probability or authenticity guarantee. Prices are compared only within the same item, condition, and authenticity category. These initial mixed-variant listings do not form a valid price benchmark.</p><h3>Evidence you can check</h3><p>Open any listing’s details to see its source, observation date, known metrics, and missing information. Manually added evidence is labelled as your input and is saved only for this session.</p></div></SheetContent></Sheet>
  <Sheet open={importOpen} onOpenChange={setImportOpen}><SheetContent className="detail-sheet"><ImportListing lane={lane} onAdd={l=>{setManualListings(old=>[{...l,searchQuery:searched},...old]);setImportOpen(false);setPlatform("all");setMessage("Listing added for this session. Seller evidence is your input, not independently verified.");}}/></SheetContent></Sheet>
 </div>;
}
function LayersIcon(){return <Package size={17}/>;}
function ListingCard({listing:l,onSelect,lowest}:{listing:Listing;onSelect:()=>void;lowest:boolean}){
 const trust=scoreListing(l);const [failed,setFailed]=useState(false);
 return <article className="listing-card"><button className="listing-image" onClick={onSelect} aria-label={`Details for ${l.title}`}>{l.image&&!failed?<img loading="lazy" src={l.image} alt={l.title} onError={()=>setFailed(true)}/>:<div className="no-photo"><Package size={38}/><span>Photo on source</span></div>}<span className="image-platform">{l.platform}</span><span className={l.match==="close"?"match-pill":"match-pill related"}>{l.match==="close"?"Close match":l.source==="research"?"Different finish":"Match unverified"}</span><span className="image-arrow"><ArrowUpRight size={18}/></span></button><div className="listing-copy"><div className="listing-brand">{l.source==="manual"?"ADDED BY YOU":l.source==="live"?"LIVE SEARCH RESULT":"RESEARCHED FIND"}{lowest&&<span>LOWEST CLOSE MATCH</span>}</div><button onClick={onSelect} className="listing-title">{l.title}</button><p className="listing-specs">{l.size} <span>·</span> {l.condition}</p><div className="price-row"><strong>{money(l.price,l.currency)}</strong><span>{l.shipping===null?"Shipping unknown":`+ ${money(l.shipping,l.currency)} shipping`}<small>Tax / fees extra</small></span></div><button className={`trust-row ${trust.score!==null&&trust.score>=80?"strong-trust":""}`} onClick={onSelect}><ShieldCheck size={17}/><span>{trust.score===null?"Seller trust unknown":`${trust.score}/100 · ${trust.label}`}</span><ChevronRight size={15}/></button><div className="card-actions"><button onClick={onSelect}>Evidence & details</button><a href={l.url} target="_blank" rel="noopener noreferrer">View listing <ArrowUpRight size={13}/></a></div></div></article>;
}
function ListingDetails({listing:l,onUpdate}:{listing:Listing;onUpdate:(l:Listing)=>void}){
 const score=scoreListing(l);
 return <><SheetHeader><span className="eyebrow">{l.platform} / EVIDENCE</span><SheetTitle>{l.title}</SheetTitle><SheetDescription>{l.authenticity}</SheetDescription></SheetHeader><div className="sheet-body"><div className="detail-price">{money(l.price,l.currency)}<span>{l.shipping===null?"Shipping unknown":`+ ${money(l.shipping,l.currency)} shipping · taxes / fees extra`}</span></div><a className="primary-button external-button" href={l.url} target="_blank" rel="noopener noreferrer">Open original listing <ArrowUpRight size={16}/></a><div className="score-panel"><ShieldCheck size={27}/><strong>{score.score===null?"—":score.score}<small>/ 100</small></strong><span>{score.label}</span><p>{Math.round(score.coverage*100)}% of evidence categories available</p></div><h3>{l.seller}</h3><dl className="evidence-grid"><dt>Recorded sales</dt><dd>{l.evidence.sold??"Unknown"}</dd><dt>Active listings</dt><dd>{l.evidence.active??"Unknown"}</dd><dt>Feedback count / score</dt><dd>{l.evidence.reviews??"Unknown"}</dd><dt>Positive feedback</dt><dd>{l.evidence.positiveRate===null?"Unknown":`${Math.round(l.evidence.positiveRate*100)}%`}</dd><dt>Account age</dt><dd>{l.evidence.accountAgeDays===null?"Unknown":`${Math.floor(l.evidence.accountAgeDays/365)}+ years`}</dd><dt>Photo evidence</dt><dd>{l.evidence.photos??"Not verified"}</dd></dl>{score.reasons.length>0&&<ul className="reason-list">{score.reasons.map(r=><li key={r}><Info size={14}/>{r}</li>)}</ul>}<h3>Before you decide</h3><p>{l.notes}</p><p className="detail-note">{l.source==="research"?"Research snapshot":l.source==="manual"?"User-entered evidence":"API / search observation"} · {l.checkedAt}. Recheck the original page. “Available” reflects what was observed then. Seller trust does not authenticate this item.</p><SellerCalculator key={l.id} listing={l} onUpdate={onUpdate}/></div></>;
}
function SellerCalculator({listing,onUpdate}:{listing:Listing;onUpdate:(l:Listing)=>void}){
 const [sold,setSold]=useState(String(listing.evidence.sold??"")),[active,setActive]=useState(String(listing.evidence.active??"")),[median,setMedian]=useState(String(listing.comparison?.median??"")),[count,setCount]=useState(String(listing.comparison?.count??"")),[saved,setSaved]=useState(false);
 const number=(v:string)=>v.trim()===""?null:Number(v);
 const result=scoreSeller({...listing.evidence,sold:number(sold),active:number(active)},{price:listing.price,median:number(median),count:number(count)??0});
 return <details className="calculator-details"><summary>Check a seller with your own evidence</summary><p>Use observed counts. Leave unavailable information blank. Comparable prices must match the item, condition, currency, and authenticity category.</p><div className="form-grid">{[["Recorded sales",sold,setSold],["Active listings",active,setActive],["Comparable median",median,setMedian],["Comparable count",count,setCount]].map(([label,value,setter])=><label key={String(label)} className="field-label">{String(label)}<input type="number" min="0" value={String(value)} placeholder="Unknown" onChange={e=>(setter as (v:string)=>void)(e.target.value)}/></label>)}</div><div className="calculated-result"><strong>{result.score??"—"} / 100</strong><span>{result.label} · based on your input</span></div>{result.reasons.map(r=><p key={r} className="microcopy">{r}</p>)}<button className="outline-button" onClick={()=>{onUpdate({...listing,evidence:{...listing.evidence,sold:number(sold),active:number(active)},comparison:{median:number(median),count:number(count)??0},notes:listing.notes+" Seller counts / price benchmark were updated with user-entered evidence."});setSaved(true);}}>{saved?"Evidence saved for this session":"Apply evidence to listing"}</button></details>;
}
function CostCalculator(){
 const labels=["Item price","Domestic shipping","International shipping","Proxy / service fees","Payment fees","Tax / duty estimate"];
 const [currency,setCurrency]=useState("CNY"),[rate,setRate]=useState(""),[values,setValues]=useState<string[]>(["","","","","",""]);
 const result=landedCost(values.map(v=>v===""?null:Number(v)),currency==="USD"?1:Number(rate));
 return <section className="cost-calculator"><div><span className="section-kicker">BEYOND THE PRICE TAG</span><h3>What will it cost to your door?</h3><p>Use the seller and proxy quotes. Enter every amount in the selected currency; use 0 only for a confirmed free cost.</p></div><div className="calculator-currency"><Select value={currency} onValueChange={v=>{setCurrency(v);setRate("");setValues(["","","","","",""]);}}><SelectTrigger aria-label="Quote currency"><SelectValue/></SelectTrigger><SelectContent>{["CNY","JPY","USD","EUR","GBP"].map(c=><SelectItem value={c} key={c}>{c}</SelectItem>)}</SelectContent></Select>{currency!=="USD"&&<label className="field-label">USD per 1 {currency}<input aria-label="USD exchange rate" type="number" step="any" min="0" value={rate} onChange={e=>setRate(e.target.value)} placeholder="Your quoted rate"/></label>}</div><div className="cost-fields">{labels.map((label,i)=><label key={label} className="field-label">{label} ({currency})<input type="number" min="0" step="any" placeholder="Unknown" value={values[i]} onChange={e=>setValues(old=>old.map((v,j)=>j===i?e.target.value:v))}/></label>)}</div><div className="cost-total"><span>{result.total===null?"Known subtotal · estimate incomplete":"Estimated delivered total"}</span><strong>{result.subtotal===null?"Add an exchange rate":money(result.total??result.subtotal)}</strong><small>{result.missing?`${result.missing} amounts still unknown` :"Based on your quotes; final carrier and customs costs may differ"}</small></div></section>;
}
function ImportListing({lane,onAdd}:{lane:Lane;onAdd:(l:Listing)=>void}){
 const [error,setError]=useState("");
 function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);let url:URL;try{url=new URL(String(f.get("url")));if(url.protocol!=="https:"||url.username||url.password)throw new Error();}catch{setError("Enter a full HTTPS listing URL.");return;}const get=(key:string)=>String(f.get(key)||"").trim();const number=(key:string)=>get(key)===""?null:Number(get(key));const price=number("price"),sold=number("sold"),active=number("active");if([price,sold,active].some(n=>n!==null&&(!Number.isFinite(n)||n<0))){setError("Amounts and counts must be zero or greater.");return;}onAdd({id:crypto.randomUUID(),title:get("title"),platform:get("platform")||url.hostname.replace("www.",""),url:url.href,price,currency:get("currency"),shipping:null,size:get("size")||"Not specified",condition:get("condition")||"Not specified",lane,seller:get("seller")||"Seller not specified",evidence:{...unknownEvidence,sold,active},availability:"unknown",match:"related",source:"manual",checkedAt:new Date().toISOString().slice(0,10),notes:get("notes")||"User-added listing. Verify item details, seller history, shipping and availability on the source.",authenticity:lane==="reps"?"User-added replica candidate · unverified":"User-added as authentic · unverified"});}
 return <><SheetHeader><span className="eyebrow">BRING YOUR OWN FIND</span><SheetTitle>Add a listing to {lane==="legit"?"Legit":"Reps"}</SheetTitle><SheetDescription>Copy evidence from the original page. Unknown is different from zero. Added listings last for this session.</SheetDescription></SheetHeader><form className="sheet-body import-form" onSubmit={add}><label className="field-label">Listing URL<input type="url" name="url" placeholder="https://…" required maxLength={2000}/></label><label className="field-label">Item title<input name="title" required maxLength={200}/></label><div className="form-grid"><label className="field-label">Marketplace<input name="platform" placeholder="Taobao, Grailed…"/></label><label className="field-label">Price<input name="price" type="number" min="0" step="any" placeholder="Unknown"/></label><label className="field-label">Currency<input name="currency" defaultValue="USD" pattern="USD|CNY|JPY|EUR|GBP|CAD|AUD" title="USD, CNY, JPY, EUR, GBP, CAD or AUD" required/></label><label className="field-label">Size<input name="size" placeholder="W30"/></label><label className="field-label">Condition<input name="condition" placeholder="Used, new…"/></label><label className="field-label">Seller<input name="seller"/></label><label className="field-label">Recorded sales<input name="sold" type="number" min="0" step="1" placeholder="Unknown"/></label><label className="field-label">Active listings<input name="active" type="number" min="0" step="1" placeholder="Unknown"/></label></div><label className="field-label">Notes / evidence<textarea name="notes" rows={4} placeholder="Condition, seller evidence, proxy requirement…"/></label>{error&&<p role="alert">{error}</p>}<button className="primary-button"><Check size={17}/>Add to results</button></form></>;
}
